Repository gonenoculer5/Perpetua-Station, pull requests merged in 2020-06, with the labels that each got.

#4 BoH Beaker Port
  code/PerpetuaCode/t5_parts.dm
  code/game/objects/items/grenades/chem_grenade.dm
  icons/PerpIcons/beakerofholding.dmi
Labels: port

#6 Initial Config Settings
  config/admin_ranks.txt
  config/admins.txt
  config/config.txt
  config/mentors.txt
  config/whitelist.txt
Labels: Tweak/fix, features

#7 Map and config fixes
  _maps/map_files/ElysianStation/elysianstation.dmm
  beestation.dme
  config/admin_ranks.txt
  config/admins.txt
  config/config.txt
  config/maps.txt
  config/title_screens/images/delaminating_issues.dmi
  config/title_screens/images/greytide_worldwide.dmi
  config/title_screens/images/janitor.dmi
  config/title_screens/images/meta_boiz.dmi
  config/title_screens/images/singuloose.dmi
  config/title_screens/images/vaporwave.dmi
Labels: Tweak/fix

#9 Modularize PR
  beestation.dme
  perpstation/code/ported/t5_parts.dm
  perpstation/icons/PerpIcons/beakerofholding.dmi
  perpstation/icons/PerpIcons/quantumbeaker_fulp.dmi
  perpstation/icons/PerpIcons/quantumbin_fulp.dmi
  perpstation/icons/PerpIcons/quantumcap_fulp.dmi
  perpstation/icons/PerpIcons/quantumcell_fulp.dmi
  perpstation/icons/PerpIcons/quantumlaser_fulp.dmi
  perpstation/icons/PerpIcons/quantummanip_fulp.dmi
  perpstation/icons/PerpIcons/quantumscan_fulp.dmi
Labels: Tweak/fix, features

#10 More config changes
  config/admin_ranks.txt
  config/motd.txt
  config/title_screens/images/extended.dmi
  config/title_screens/images/station.dmi
  icons/perpetua_64.png
  interface/skin.dmf
Labels: Tweak/fix, features

#11 Changelog and Link changes
  config/config.txt
  html/changelog.html
Labels: Tweak/fix

#12 AI Laws port 2: Electric Boogaloo
  beestation.dme
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/AI_modules.dm
  config/game_options.txt
  perpstation/code/datums/ai_laws/ai_laws_perp.dm
Labels: features, port

#14 Elysian Fixes
  _maps/map_files/ElysianStation/elysianstation.dmm
Labels: Tweak/fix

#15 Adds new title music, Title1 and Nightdrive
  config/title_music/sounds/nightdrive.ogg
  config/title_music/sounds/perptitle1.ogg
Labels: features

#17 Elysian fixes and additions
  _maps/map_files/ElysianStation/elysianstation.dmm
Labels: Tweak/fix, features

#18 New TG Titanium Walls and other updated turfs
  icons/turf/walls/shuttle_wall.dmi
Labels: port

#19 Adds Custom Perpetua Station plaque
  austation/icons/obj/turf/plaque.dmi
  code/game/objects/effects/decals/turfdecal/markings.dm
  perpstation/icons/obj/turf/plaque.dmi
Labels: features

#20 More Config Changes
  config/antag_rep.txt
  config/austation.txt
  config/config.txt
  config/game_options.txt
  config/in_character_filter.txt
Labels: Tweak/fix

#21 New Title Images
  config/title_screens/images/maint.dmi
  config/title_screens/images/station.dmi
  config/title_screens/images/wishyouwerehere.dmi
Labels: features

#22 WINTERCOATS
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: features, port

#23 Prisoner Port
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/ElysianStation/elysianstation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/jobs.dm
  config/jobs.txt
  config/title_screens/images/maint.dmi
  config/title_screens/images/station.dmi
  config/title_screens/images/wishyouwerehere.dmi
  icons/mob/landmarks.dmi
  perpstation/code/ported/t5_parts.dm
Labels: port

#25 New Title Images
  config/title_screens/images/BoxStation+void.dmi
  config/title_screens/images/Deltastation+wishyouwerehere.dmi
Labels: Tweak/fix, features
